config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('watchdog_kj_kultura.users.urls', namespace='users')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

watchdog_kj_kultura/main/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views import defaults as default_views
from django.views.generic import TemplateView
from watchdog_kj_kultura.teryt.sitemaps import JSTSitemap
from watchdog_kj_kultura.organizations.sitemaps import OrganizationSitemap
from watchdog_kj_kultura.staticpages.sitemaps import PageSitemap
from django.contrib.sitemaps import views as sitemap_views

from . import views

sitemaps = {
    'teryt': JSTSitemap,
    'organization': OrganizationSitemap,
    'page': PageSitemap,
}

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    url(_(r'^search/'), views.CustomFacetedSearchView.as_view(), name="haystack_search"),

    # User management
    url(_(r'^organizations/'), include('watchdog_kj_kultura.organizations.urls',
                                       namespace='organizations')),
    url(_(r'^region/'), include('watchdog_kj_kultura.teryt.urls', namespace="teryt")),
    url(_(r'^requests/'), include('watchdog_kj_kultura.organizations_requests.urls',
                                  namespace="organizations_requests")),
    url(_(r'^pages/'), include('watchdog_kj_kultura.staticpages.urls', namespace="staticpages")),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

watchdog_kj_kultura/organizations/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.OrganizationListView.as_view(),
        name="list"),
    url(r'^data.geojson$', views.OrganizationMapLayer.as_view(), name='data'),
    url(r'^data-(?P<z>\d+)-(?P<x>\d+)-(?P<y>\d+).geojson$',
        views.OrganizationTiledGeoJSONLayerView.as_view(), name='data'),
    url(_(r'^region-(?P<region>[\w\d-]+)$'), views.OrganizationListView.as_view(),
        name="list"),
    url(_(r'^organization-(?P<slug>[\w\d-]+)$'), views.OrganizationDetailView.as_view(),
        name="details"),
    url(_(r'^organization-(?P<slug>[\w\d-]+)/~fix$'), views.OrganizationFixView.as_view(),
        name="fix"),
    url(r'^(?P<category>[\w\d-]+)$', views.OrganizationListView.as_view(),
        name="list"),
]

watchdog_kj_kultura/main/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel
from tinymce.models import HTMLField
from django.contrib.sites.models import Site


class SettingsQuerySet(models.QuerySet):
    pass


class Settings(TimeStampedModel):
    site = models.OneToOneField(Site, verbose_name=_("Site"))
    home_content = HTMLField(verbose_name=_("Content of home page"))
    objects = SettingsQuerySet.as_manager()

    class Meta:
        verbose_name = _("Settings")
        verbose_name_plural = _("Settings")
        ordering = ['created', ]

watchdog_kj_kultura/main/views.py
from django.core.exceptions import ImproperlyConfigured
from haystack.forms import FacetedSearchForm
from haystack.generic_views import FacetedSearchView
from .compat import get_model
from ..teryt.models import JST
from watchdog_kj_kultura.organizations.models import Category


class BreadcrumbsMixin(object):

    def get_breadcrumbs(self):
        raise ImproperlyConfigured(
            '{0} is missing a breadcrumbs. Define override ' +
            '{0}.get_url().'.format(self.__class__.__name__))

    def get_context_data(self, **kwargs):
        context = super(BreadcrumbsMixin, self).get_context_data(**kwargs)
        context['breadcrumbs'] = self.get_breadcrumbs()
        return context


class CustomFacetedSearchView(FacetedSearchView):
    form_class = FacetedSearchForm
    facet_fields = ['jst', 'django_ct', 'category']

    def _prefetch_by_slug(self, model, field):
        ids = [key for key, count in field]
        object_dict = {obj.slug: obj for obj in model.objects.filter(slug__in=ids).all()}
        return [(object_dict.get(key, key), key, count)
                for key, count in field]

    def prefetch_jst(self, field):
        return self._prefetch_by_slug(JST, field)

    def prefetch_category(self, field):
        return self._prefetch_by_slug(Category, field)

    def prefetch_django_ct(self, field):
        result = []

        for key, count in field:
            model = get_model(*key.split('.', 2))
            name = model._meta.verbose_name_plural
            result.append((name, key, count))
        return result

    def get_context_data(self, *args, **kwargs):
        context = super(CustomFacetedSearchView, self).get_context_data(*args, **kwargs)
        if 'fields' in context['facets']:
            context['jst'] = self.prefetch_jst(context['facets']['fields']['jst'])
            context['category'] = self.prefetch_category(context['facets']['fields']['category'])
            context['django_ct'] = self.prefetch_django_ct(context['facets']['fields']['django_ct'])
        return context

watchdog_kj_kultura/main/templates/pages/about.html
{% extends "base.html" %}

watchdog_kj_kultura/main/templates/pages/home.html
{% extends 'base.html' %}
{% load i18n static %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block title %}Zobacz, jak państwo wspiera kulturę! - {% trans "watchdog-kj-kultura" %}{% endblock title %}

{% block body_classes %}navbar-without-margin{% endblock body_classes %}

{% block css %}
  {{block.super}}
  {% leaflet_js %}
  {% leaflet_css %}
{% endblock %}

{% block main %}
  <div class="jumbotron main-header">
    <div class="container">
      <h1>Zobacz, jak państwo wspiera kulturę!</h1>
      <p>W Polsce działają tysiące instytucji kultury finansowanych z naszych podatków. Korzystajmy z ich pracy, wpływajmy na ich kształt i pozyskujmy informacje na temat ich pracy! </p>
      <p>Szukaj instytucji w Twojej okolicy! </p>
      <div class="row">
        <div class="col-xs-12 col-md-4 col-md-push-4">
            {% include "partials/_search_form.html" %}
        </div>
      </div>
    </div>
    <ul class="main-header__slideshow">
        <li><span></span></li>
        <li><span></span></li>
        <li><span></span></li>
        <li><span></span></li>
        <li><span></span></li>
        <li><span></span></li>
    </ul>
  </div>
  <div class="section section-features">
    <div class="container">
      <h2 class="heading-accent">Co możesz zrobić?</h2>
      <div class="row">
        <div class="col-md-6">
          <div class="text-center">
            <i class="fa fa-bar-chart fa-5x" aria-hidden="true"></i>
          </div>
          <h3 class="heading-accent">Przejrzeć dane zgromadzone przez nas</h3>
          <p>Zgromadziliśmy dane kontaktowe do ok. 4000 instytucji kultury. Możesz je uzupełniać i aktualizować.</p>
        </div>
        <div class="col-md-6">
          <div class="text-center">
            <i class="fa fa-pencil fa-5x" aria-hidden="true"></i>
          </div>
          <h3 class="heading-accent">Wysłać wniosek o informację publiczną lub petycję</h3>
          <p>Chcesz pozyskać dane o pracy instytucji kultury w Twojej okolicy? Może chciałbyś wpłynąć na jej prace? Nasz serwis to umożliwia</p>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
    {% leaflet_map "main" callback="main_map_init" %}
    </div>
  </div>
  <div class="section section-features">
    <div class="container">
      <h2 class="heading-accent">Jakie dane udostępniamy?</h2>
      <div class="row">
        <div class="col-md-6">
          <div class="text-center">
            <i class="fa fa-address-card-o fa-5x" aria-hidden="true"></i>
          </div>
          <h3 class="heading-accent">Dane adresowe i kontaktowe</h3>
          <p>Zebraliśmy adresy, e-maile, strony w Biuletynu Informacji Publicznej… Chcemy pomóc Obywatelom dotrzeć od instytucji, które współfinansują!</p>
        </div>
        <div class="col-md-6">
          <div class="text-center">
            <i class="fa fa-money fa-5x" aria-hidden="true"></i>
          </div>
          <h3 class="heading-accent">Dane o finansowaniu, wydatkach i zatrudnieniu</h3>
          <p>Wniosek o udostępnienie danych dotyczących finansowania, wydatków i zatrudnieniu wysłaliśmy na  3975 adresów e-mail instytucji kultury. Odpowiedź uzyskaliśmy od 799 z nich. </p>
        </div>
      </div>
    </div>
  </div>
  <div class="section section-support">
    <div class="container">
      <div class="section-content">
        <div class="row">
          <div class="col-md-3 col-md-offset-3">
            <h2>Kim jesteśmy?</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <img src="{% static 'img/logo-kj-big.png' %}" alt="Klub Jagielloński" class="img-responsive">
          </div>
          <div class="col-md-9">
            <p>Klub Jagielloński jest ogólnopolskim środowiskiem działaczy obywatelskich, publicystów i ekspertów młodego pokolenia pracujących razem na rzecz dobra wspólnego. Prowadzimy działalność edukacyjną, społeczną, wydawniczą i analityczną oraz realizujemy oddolne inicjatywy polityczne zachowując niezależność od partii i innych organizacji politycznych.</p>
            <p>Wydajemy pismo „Pressje” i portal jagiellonski24.pl. Realizujemy Akademię Nowoczesnego Patriotyzmu, w ramach której uczymy młodych ludzi poważnego podejścia do polityki i zachęcamy do wpływania na życie ich lokalnej społeczności. Stworzyliśmy aplikację Pola, dzięki której już ponad 330 000 Polaków pozyskuje szczegółowe informacje o kupowanych przez siebie produktach. Tworzymy ekspertyzy i raporty w ramach Centrum Analiz Klubu Jagiellońskiego, które zrzesza blisko 100 ekspertów różnych specjalizacji. Prowadzimy poradnie prawne w kilkunastu miastach południowej Polski. Każdego roku organizujemy szereg mniejszych projektów społecznych i kulturalnych. </p>
            <p>Chcesz do nas dołączyć? Regularnie spotykamy się już w Krakowie, Warszawie, Łodzi, Katowicach, Gdańsku, Poznaniu, Toruniu, Lublinie, Szczecinie i Rzeszowie!  Skontaktuj się z koordynatorem z najbliższego od działu i zacznij z nami zmieniać Polskę na lepsze.</p>
            <p class="text-center">
              <a href="http://kj.org.pl/o-klubie/oddzialy/" class="btn btn-primary btn-lg">Skontaktuj się z nami</a>
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="section section-partners">
    <div class="container">

      <div class="row">
        <div class="col-md-6">
          <h2 class="heading-accent">Dofinansowano ze środków:</h2>
          <div class="partner">
            <a href="http://www.mkidn.gov.pl/">
              <img src="{% static 'img/logo-mkidn.jpg' %}" alt="Ministerstwo Kultury i Dziedzictwa Narodowego">
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <h2 class="heading-accent">Wykonanie: </h2>
          <div class="partner">
            <a href="https://siecobywatelska.pl/">
              <img src="{% static 'img/logo-sowp.png' %}" alt="Sieć Obywatelska Watchdog Polska">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
  function main_map_init (map, options) {
      var geojsonMarkerOptions = {
          radius: 8,
          fillColor: "#ff7800",
          color: "#000",
          weight: 1,
          opacity: 1,
          fillOpacity: 0.8
      };

      map.scrollWheelZoom.disable()

      var dataurl = '{% url "organizations:data" %}';
      $.getJSON(dataurl, function (data) {
          L.geoJson(data, {
              pointToLayer: function (feature, latlng) {
                  var marker = L.circleMarker(latlng, geojsonMarkerOptions);
                  marker.bindPopup('<a href="' + feature.properties.absolute_url + '">' + feature.properties.name + '</a>');
                  return marker;
              }
          }).addTo(map);
      });
  };
  </script>
{% endblock %}